# Generated by Django 5.1.2 on 2024-10-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='Boots',
        ),
        migrations.RemoveField(
            model_name='door',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='cornice',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='door',
            name='cornice',
        ),
        migrations.RemoveField(
            model_name='door',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='door',
            name='casing',
        ),
        migrations.RemoveField(
            model_name='door',
            name='podium',
        ),
        migrations.RemoveField(
            model_name='door',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='molding',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='podium',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='socket',
            name='Shape',
        ),
        migrations.DeleteModel(
            name='Boots',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Cornice',
        ),
        migrations.DeleteModel(
            name='Door',
        ),
        migrations.DeleteModel(
            name='Molding',
        ),
        migrations.DeleteModel(
            name='Podium',
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.DeleteModel(
            name='Socket',
        ),
    ]
