# Generated by Django 5.1.2 on 2024-10-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='Boots',
            new_name='boots',
        ),
    ]
