# Generated by Django 5.1.2 on 2024-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0005_rename_casing_door_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='cover_type',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='has_groove',
        ),
        migrations.AddField(
            model_name='shape',
            name='bevel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shape',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
        migrations.AlterField(
            model_name='shape',
            name='image',
            field=models.ImageField(upload_to='shape/'),
        ),
    ]
