# Generated by Django 5.1.2 on 2024-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0006_remove_door_cover_type_remove_shape_has_groove_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boots',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='cornice',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='podium',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='portal',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='shape',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='socket',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='boots',
            name='image',
            field=models.ImageField(upload_to='boots/'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='image',
            field=models.ImageField(upload_to='portals/'),
        ),
    ]
