# Generated by Django 5.1.2 on 2024-10-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0008_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='bevel',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
