# Generated by Django 5.1.2 on 2024-10-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0010_molding_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romerio.collection')),
            ],
        ),
    ]
