# Generated by Django 5.1.2 on 2024-10-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0013_bevels_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='bevel',
        ),
        migrations.AddField(
            model_name='shape',
            name='has_bevel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
