# Generated by Django 5.1.2 on 2024-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0014_remove_shape_bevel_shape_has_bevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bevels',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Bevel'),
        ),
        migrations.AddField(
            model_name='boots',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Boots/'),
        ),
        migrations.AddField(
            model_name='colors',
            name='hex',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='cornice',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Carnice/'),
        ),
        migrations.AddField(
            model_name='molding',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Molding'),
        ),
        migrations.AddField(
            model_name='podium',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Podium/'),
        ),
        migrations.AddField(
            model_name='portal',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Portal/'),
        ),
        migrations.AddField(
            model_name='shape',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Shape/'),
        ),
        migrations.AddField(
            model_name='socket',
            name='icon',
            field=models.ImageField(default='none', upload_to='icon/Socket/'),
        ),
        migrations.AlterField(
            model_name='molding',
            name='color',
            field=models.CharField(default='Standard', max_length=255),
        ),
    ]
