# Generated by Django 5.1.2 on 2024-10-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0016_shape_glass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='grid/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.ImageField(default='none', upload_to='icon/Grid')),
                ('Shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.shape')),
                ('collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romerio.collection')),
            ],
        ),
    ]
