# Generated by Django 5.1.2 on 2024-10-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0019_remove_boots_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornice',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='podium',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='socket',
            name='Shape',
        ),
        migrations.AddField(
            model_name='boots',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
        migrations.AddField(
            model_name='cornice',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
        migrations.AddField(
            model_name='door',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
        migrations.AddField(
            model_name='podium',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
        migrations.AddField(
            model_name='portal',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
        migrations.AddField(
            model_name='socket',
            name='cover_type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=7),
        ),
    ]
