# Generated by Django 5.1.2 on 2024-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0020_remove_cornice_shape_remove_podium_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boots',
            name='size',
            field=models.CharField(choices=[('Size-1', 'Размер-1'), ('Size-2', 'Размер-2')], default='Size-1', max_length=255),
        ),
        migrations.AddField(
            model_name='cornice',
            name='size',
            field=models.CharField(choices=[('Size-1', 'Размер-1'), ('Size-2', 'Размер-2')], default='Size-1', max_length=255),
        ),
        migrations.AddField(
            model_name='podium',
            name='size',
            field=models.CharField(choices=[('Size-1', 'Размер-1'), ('Size-2', 'Размер-2')], default='Size-1', max_length=255),
        ),
        migrations.AddField(
            model_name='portal',
            name='size',
            field=models.CharField(choices=[('Size-1', 'Размер-1'), ('Size-2', 'Размер-2')], default='Size-1', max_length=255),
        ),
        migrations.AddField(
            model_name='socket',
            name='size',
            field=models.CharField(choices=[('Size-1', 'Размер-1'), ('Size-2', 'Размер-2')], default='Size-1', max_length=255),
        ),
    ]
