# Generated by Django 5.1.2 on 2024-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0021_boots_size_cornice_size_podium_size_portal_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='bevel',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='grid',
            name='bevel_image',
            field=models.ImageField(blank=True, null=True, upload_to='grid/'),
        ),
    ]
