# Generated by Django 5.1.2 on 2024-10-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0022_grid_bevel_grid_bevel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('Emal', 'Эмаль'), ('Shpone', 'Шпон')], default='Emal', max_length=255),
        ),
    ]
