# Generated by Django 5.1.2 on 2024-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0023_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bevels',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
