# Generated by Django 5.1.2 on 2024-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0024_alter_bevels_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='bevel_image',
        ),
        migrations.AddField(
            model_name='grid',
            name='bevel_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/grid/'),
        ),
    ]
