# Generated by Django 5.1.2 on 2024-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0025_remove_grid_bevel_image_grid_bevel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='cover_type',
            field=models.CharField(choices=[('DO', 'DO'), ('Classic', 'Classic')], default='Shpone', max_length=7),
        ),
    ]
