# Generated by Django 5.1.2 on 2024-10-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0027_alter_bevels_price_alter_boots_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='cover_type',
        ),
        migrations.AddField(
            model_name='door',
            name='bevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.bevels'),
        ),
        migrations.AddField(
            model_name='door',
            name='cliend_id',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='door',
            name='grid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='grid_bevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='molding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.molding'),
        ),
        migrations.AlterField(
            model_name='door',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.boots'),
        ),
        migrations.AlterField(
            model_name='door',
            name='cornice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.cornice'),
        ),
        migrations.AlterField(
            model_name='door',
            name='podium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.podium'),
        ),
        migrations.AlterField(
            model_name='door',
            name='socket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romerio.socket'),
        ),
    ]
