# Generated by Django 5.1.2 on 2024-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0028_remove_door_cover_type_door_bevel_door_cliend_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='cliend_id',
            field=models.CharField(max_length=255),
        ),
    ]
