# Generated by Django 5.1.2 on 2024-10-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0029_alter_door_cliend_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='cliend_id',
            new_name='client_id',
        ),
    ]
