# Generated by Django 5.1.2 on 2024-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0030_rename_cliend_id_door_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='Cart_icon',
            field=models.ImageField(default='none', upload_to='icons/Shape/'),
        ),
    ]
