# Generated by Django 5.1.2 on 2024-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0031_shape_cart_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='color_hex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
