# Generated by Django 5.1.2 on 2024-11-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0032_door_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=10, null=True),
        ),
    ]
