# Generated by Django 5.1.2 on 2024-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romerio', '0033_door_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='molding_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
